fundot.accs = fundot.accs or {}

fundot.accs['test'] = {
	[1] = {
		["children"] = {
			[1] = {
				["children"] = {
				},
				["self"] = {
					["DrawOrder"] = 0,
					["UniqueID"] = "85b7d70fd9f867d25cf07536d4b8c672b6ee66ff71c075afb34f9c2abc1cecf0",
					["Hide"] = false,
					["TargetEntityUID"] = "",
					["EditorExpand"] = true,
					["OwnerName"] = "self",
					["IsDisturbing"] = false,
					["Name"] = "watch or bracelet",
					["Duplicate"] = false,
					["ClassName"] = "group",
				},
			},
			[2] = {
				["children"] = {
				},
				["self"] = {
					["Skin"] = 0,
					["UniqueID"] = "230d170535eea288fa58bed0fe5207b1139f8788a7461124ed651af101c53a62",
					["NoLighting"] = false,
					["AimPartName"] = "",
					["IgnoreZ"] = false,
					["AimPartUID"] = "",
					["Materials"] = "",
					["Name"] = "",
					["LevelOfDetail"] = 8,
					["NoTextureFiltering"] = true,
					["PositionOffset"] = Vector(0, 0, 0),
					["IsDisturbing"] = false,
					["EyeAngles"] = false,
					["DrawOrder"] = 0,
					["TargetEntityUID"] = "",
					["Alpha"] = 1,
					["Material"] = "",
					["Invert"] = false,
					["ForceObjUrl"] = false,
					["Bone"] = "spine 2",
					["Angles"] = Angle(1.3267946243286, 89.999015808105, 91.000274658203),
					["AngleOffset"] = Angle(0, 0, 0),
					["BoneMerge"] = false,
					["Color"] = Vector(1, 1, 1),
					["Position"] = Vector(-51.224731445313, 3.0595703125, 1.1865234375),
					["ClassName"] = "model2",
					["Brightness"] = 1,
					["Hide"] = false,
					["NoCulling"] = false,
					["Scale"] = Vector(1, 1, 1),
					["LegacyTransform"] = false,
					["EditorExpand"] = false,
					["Size"] = 1.025,
					["ModelModifiers"] = "",
					["Translucent"] = false,
					["BlendMode"] = "",
					["EyeTargetUID"] = "",
					["Model"] = "https://drive.google.com/file/d/1vFb4TFF2aW0pPNiPKltvF3Gq8lPvub8q/view?usp=sharing",
				},
			},
			[3] = {
				["children"] = {
				},
				["self"] = {
					["Skin"] = 0,
					["UniqueID"] = "54d74b10c59517f1964b8a9f3ad354e3663c6f11170ca138cda1ee913642ffb1",
					["NoLighting"] = false,
					["AimPartName"] = "",
					["IgnoreZ"] = false,
					["AimPartUID"] = "",
					["Materials"] = "",
					["Name"] = "",
					["LevelOfDetail"] = 0,
					["NoTextureFiltering"] = true,
					["PositionOffset"] = Vector(0, 0, 0),
					["IsDisturbing"] = false,
					["EyeAngles"] = false,
					["DrawOrder"] = 0,
					["TargetEntityUID"] = "",
					["Alpha"] = 1,
					["Material"] = "",
					["Invert"] = false,
					["ForceObjUrl"] = false,
					["Bone"] = "head",
					["Angles"] = Angle(-87.189224243164, -80.219741821289, 33.6565284729),
					["AngleOffset"] = Angle(0, 0, 0),
					["BoneMerge"] = false,
					["Color"] = Vector(1, 1, 1),
					["Position"] = Vector(2.21826171875, -0.208984375, -0.0283203125),
					["ClassName"] = "model2",
					["Brightness"] = 1,
					["Hide"] = false,
					["NoCulling"] = false,
					["Scale"] = Vector(1, 1, 1),
					["LegacyTransform"] = false,
					["EditorExpand"] = false,
					["Size"] = 1,
					["ModelModifiers"] = "",
					["Translucent"] = false,
					["BlendMode"] = "",
					["EyeTargetUID"] = "",
					["Model"] = "models/props_silo/welding_helmet.mdl",
				},
			},
			[4] = {
				["children"] = {
				},
				["self"] = {
					["Skin"] = 0,
					["UniqueID"] = "8b8ad4d43df67ff0c0f3bfcd0ce94802fd092ef998d348316f7f1c24a47f2405",
					["NoLighting"] = false,
					["BlendMode"] = "",
					["AimPartUID"] = "",
					["Materials"] = "",
					["Name"] = "",
					["LevelOfDetail"] = 0,
					["NoTextureFiltering"] = true,
					["InverseKinematics"] = true,
					["PositionOffset"] = Vector(0, 0, 0),
					["NoCulling"] = false,
					["Brightness"] = 1,
					["DrawOrder"] = 0,
					["TargetEntityUID"] = "",
					["DrawShadow"] = true,
					["Alpha"] = 1,
					["Material"] = "",
					["CrouchingHullHeight"] = 36,
					["Model"] = "",
					["ModelModifiers"] = "",
					["NoDraw"] = false,
					["IgnoreZ"] = false,
					["HullWidth"] = 32,
					["Translucent"] = false,
					["Position"] = Vector(0, 0, 0),
					["LegacyTransform"] = false,
					["ClassName"] = "entity2",
					["Hide"] = false,
					["IsDisturbing"] = false,
					["Scale"] = Vector(1, 1, 1),
					["Color"] = Vector(1, 1, 1),
					["EditorExpand"] = false,
					["Size"] = 1,
					["Invert"] = false,
					["Angles"] = Angle(0, 0, 0),
					["AngleOffset"] = Angle(0, 0, 0),
					["EyeTargetUID"] = "",
					["StandingHullHeight"] = 72,
				},
			},
			[5] = {
				["children"] = {
					[1] = {
						["children"] = {
						},
						["self"] = {
							["AffectChildrenOnly"] = false,
							["DrawOrder"] = 0,
							["TargetPartUID"] = "",
							["Name"] = "",
							["Event"] = "weapon_class",
							["Hide"] = false,
							["TargetEntityUID"] = "",
							["RootOwner"] = true,
							["EditorExpand"] = false,
							["ClassName"] = "event",
							["Arguments"] = "weapon_crowbar@@1",
							["Invert"] = false,
							["IsDisturbing"] = false,
							["Operator"] = "equal",
							["UniqueID"] = "72c9c0751e1e3fdf6285cef98df175edf398db318b622ee77b0d9bde50a9869c",
							["ZeroEyePitch"] = false,
						},
					},
				},
				["self"] = {
					["DrawOrder"] = 0,
					["UniqueID"] = "46e7fef8740426d899c91362074dd7f71ac1a8e7057af22b2d228d60e92b3de7",
					["Hide"] = false,
					["TargetEntityUID"] = "",
					["EditorExpand"] = true,
					["OwnerName"] = "self",
					["IsDisturbing"] = false,
					["Name"] = "",
					["Duplicate"] = false,
					["ClassName"] = "group",
				},
			},
			[6] = {
				["children"] = {
					[1] = {
						["children"] = {
						},
						["self"] = {
							["AffectChildrenOnly"] = false,
							["DrawOrder"] = 0,
							["TargetPartUID"] = "",
							["Name"] = "",
							["Event"] = "weapon_class",
							["Hide"] = false,
							["TargetEntityUID"] = "",
							["RootOwner"] = true,
							["EditorExpand"] = false,
							["ClassName"] = "event",
							["Arguments"] = "weapon_crowbar@@1",
							["Invert"] = true,
							["IsDisturbing"] = false,
							["Operator"] = "equal",
							["UniqueID"] = "e55c74b06a77285edb67927041b65363a7f5373d505ded790a15571b7ec038a8",
							["ZeroEyePitch"] = false,
						},
					},
					[2] = {
						["children"] = {
						},
						["self"] = {
							["Walk"] = "walk_melee2",
							["DrawOrder"] = 0,
							["UniqueID"] = "80c3f56bdd151632f0483acf225c8e5b9c75b0858d67255f808bd94e4d52ff64",
							["AlternativeRate"] = false,
							["Jump"] = "jump_melee2",
							["AttackStandPrimaryfire"] = "aimlayer_melee2",
							["TargetEntityUID"] = "",
							["Run"] = "run_melee2",
							["CrouchIdle"] = "cidle_melee2",
							["CrouchWalk"] = "cwalk_melee2",
							["Sitting"] = "",
							["Name"] = "",
							["ActRangeAttack1"] = "aimlayer_melee2",
							["Fallback"] = "",
							["ReloadCrouch"] = "",
							["ReloadStand"] = "",
							["Noclip"] = "",
							["Hide"] = false,
							["SwimIdle"] = "swim_idle_melee2",
							["Swim"] = "swimming_melee2",
							["AttackCrouchPrimaryfire"] = "aimlayer_melee2_crouch",
							["ClassName"] = "holdtype",
							["Air"] = "",
							["EditorExpand"] = false,
							["IsDisturbing"] = false,
							["StandIdle"] = "idle_melee2",
							["Override"] = false,
							["ActLand"] = "",
						},
					},
				},
				["self"] = {
					["DrawOrder"] = 0,
					["UniqueID"] = "c755307c8f1d8c4c809bca39f980d43700aa80784080ad9e293bf67f65405b82",
					["Hide"] = false,
					["TargetEntityUID"] = "",
					["EditorExpand"] = true,
					["OwnerName"] = "self",
					["IsDisturbing"] = false,
					["Name"] = "",
					["Duplicate"] = false,
					["ClassName"] = "group",
				},
			},
		},
		["self"] = {
			["DrawOrder"] = 0,
			["UniqueID"] = "761d49b6b62b0a4ac9a203d51346649318d316f0206f51a82b3a4b233180b3e8",
			["Hide"] = false,
			["TargetEntityUID"] = "",
			["EditorExpand"] = true,
			["OwnerName"] = "self",
			["IsDisturbing"] = false,
			["Name"] = "my outfit",
			["Duplicate"] = false,
			["ClassName"] = "group",
		},
	},	
}